# Generated by Django 4.2 on 2023-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatTranslation', '0002_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.IntegerField(default=1204098649),
        ),
    ]
